name: AWS STS Get Caller Identity

on:
  push:

permissions:
  id-token: write   # necessário para o OIDC
  contents: read    # necessário para actions/checkout

jobs:
  aws-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Debug OIDC token
        run: |
          echo "Repo: ${{ github.repository }}"
          echo "Ref: ${{ github.ref }}"
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET }}
          aws-region: us-east-1
      
      - name: STS Get Caller Identity
        run: aws sts get-caller-identity
