name: AWS OIDC Test

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Test without AWS credentials
        run: |
          echo "Workflow executado com sucesso."

  deploy:
    name: AWS Deploy

    if: github.event_name != 'pull_request'

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # 1. GitHub OIDC -> github-actions
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: arn:aws:iam::012848347268:role/github-actions
          aws-region: us-east-1
          audience: sts.amazonaws.com

      # 2. github-actions -> sb-terraform
      - name: Assume Terraform Role
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: arn:aws:iam::012848347268:role/sb-gha-terraform
          aws-region: us-east-1
          role-chaining: true

      # 3. Verify final AWS identity
      - name: Verify AWS identity
        run: |
          aws sts get-caller-identity